version: "3.9"
services:
  postgres:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "bookstore"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data